package com.nahora.model.enums;

public enum TipoNotificacao {
    NOVO_PEDIDO, NOVA_PROPOSTA, PROPOSTA_ACEITA, NOVA_MENSAGEM, SERVICO_CONCLUIDO, PAGAMENTO_LIBERADO,
    DISPUTA_ABERTA, AVALIACAO_RECEBIDA, VERIFICACAO_APROVADA
}
