ALTER TABLE pedido DROP CONSTRAINT IF EXISTS fk_pedido_categoria;

ALTER TABLE pedido DROP COLUMN IF EXISTS categoria_id;

ALTER TABLE pedido ADD COLUMN IF NOT EXISTS categoria VARCHAR(50) NOT NULL DEFAULT 'ELETRICA';

DROP TABLE IF EXISTS categoria_servico;
