ALTER TABLE profissional ADD COLUMN IF NOT EXISTS logradouro  VARCHAR(255);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS numero      VARCHAR(50);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS complemento VARCHAR(255);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS bairro      VARCHAR(255);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS cidade      VARCHAR(255);
ALTER TABLE profissional ADD COLUMN IF NOT EXISTS estado      VARCHAR(2);
